import Foundation
import Herd

public struct LLMWikiLintReport: Sendable, Equatable {
    public let pageCount: Int
    public let sourceCount: Int
    public let orphanPages: [String]
    public let pagesMissingSourceCitations: [String]
    public let uncitedSources: [String]
    public let invalidWikiLinks: [String]
    public let malformedLogRecords: [Int]
    public let missingAuthorities: [String]
    public let schemaIsValid: Bool
    public let indexIsFresh: Bool

    public init(
        pageCount: Int,
        sourceCount: Int,
        orphanPages: [String],
        pagesMissingSourceCitations: [String] = [],
        uncitedSources: [String] = [],
        invalidWikiLinks: [String] = [],
        malformedLogRecords: [Int] = [],
        missingAuthorities: [String] = [],
        schemaIsValid: Bool = true,
        indexIsFresh: Bool = true
    ) {
        self.pageCount = pageCount
        self.sourceCount = sourceCount
        self.orphanPages = orphanPages
        self.pagesMissingSourceCitations = pagesMissingSourceCitations
        self.uncitedSources = uncitedSources
        self.invalidWikiLinks = invalidWikiLinks
        self.malformedLogRecords = malformedLogRecords
        self.missingAuthorities = missingAuthorities
        self.schemaIsValid = schemaIsValid
        self.indexIsFresh = indexIsFresh
    }

    public var isHealthy: Bool {
        orphanPages.isEmpty
            && pagesMissingSourceCitations.isEmpty
            && uncitedSources.isEmpty
            && invalidWikiLinks.isEmpty
            && malformedLogRecords.isEmpty
            && missingAuthorities.isEmpty
            && schemaIsValid
            && indexIsFresh
    }
}

/// The bounded, read-only material needed by GOAT's native LLM Wiki map. Names remain inside
/// the provider boundary so UI clients never need to reverse-engineer opaque entry IDs.
public struct LLMWikiGraphPage: Sendable, Equatable {
    public let entry: MemoryBrowserEntry
    public let name: String
    public let content: String

    public init(entry: MemoryBrowserEntry, name: String, content: String) {
        self.entry = entry
        self.name = name
        self.content = content
    }
}

public struct LLMWikiGraphSource: Sendable, Equatable {
    public let entry: MemoryBrowserEntry
    public let name: String

    public init(entry: MemoryBrowserEntry, name: String) {
        self.entry = entry
        self.name = name
    }
}

public struct LLMWikiGraphMaterial: Sendable, Equatable {
    public let pages: [LLMWikiGraphPage]
    public let sources: [LLMWikiGraphSource]
    /// The map is intentionally a bounded exploration surface, never an unbounded secondary
    /// index over every durable document.
    public let isTruncated: Bool

    public init(
        pages: [LLMWikiGraphPage],
        sources: [LLMWikiGraphSource],
        isTruncated: Bool = false
    ) {
        self.pages = pages
        self.sources = sources
        self.isTruncated = isTruncated
    }
}

/// Karpathy-style local wiki with separate immutable source capture and curated recall.
///
/// `raw/` is only populated through `ingest`; callers never receive a mutable raw-store handle.
/// `wiki/` is the LLM-maintained, linked Markdown layer and is the sole source for prompts and
/// the ordinary memory browser. Root-level `AGENTS.md`, `index.md`, and `log.md` are generated
/// provider authorities, not ordinary notes. This keeps archival source material out of prompt
/// budgeting while making the maintenance workflow durable and independently lintable.
public actor LLMWikiMemoryStore: EditableMemoryStore {
    public static let maximumQueryCharacters = 256
    public static let maximumQueryResults = 20
    public static let maximumGraphPages = 96
    public static let maximumGraphSources = 144
    public static let maximumGraphPageContentBytes = 64 * 1_024
    public nonisolated let capabilities = MemoryStoreCapabilities([
        .promptSnapshot, .browse, .remember, .edit, .delete,
    ])

    private static let maximumLifecycleLogBytes = 1 * 1_024 * 1_024
    private static let agentsFileName = "AGENTS.md"
    private static let indexFileName = "index.md"
    private static let logFileName = "log.md"
    private static let indexHeader = """
        # LLM Wiki index

        > Generated by GOAT from curated wiki page frontmatter. Edit pages, not this index.

        """
    private static let logHeader = """
        # LLM Wiki log

        > Append-only GOAT operation records. Do not edit or reorder entries.

        """
    private static let agentsContents = """
        # GOAT LLM Wiki maintenance contract

        This directory is one LLM Wiki provider authority. The model may read immutable sources in
        `raw/` and maintain derived, canonical Markdown pages in `wiki/`. It must never edit or
        delete a raw source. `index.md` and `log.md` are generated provider authorities, not wiki
        pages.

        ## Required workflow

        1. Call `wiki_ingest_source` for bounded source material and retain the returned raw ID.
        2. Read that source before changing curated pages.
        3. Write or revise canonical `wiki/` pages with exact `[[page-name]]` links and exact
           `[[source-uuid]]` citations for claims drawn from raw material.
        4. Use `wiki_query` to start from the generated index and read selected curated pages.
        5. Call `wiki_lint` before declaring maintenance complete. Resolve reported schema, index,
           citation, link, orphan, or log issues through ordinary curated-page changes.

        Contradictions are durable information: record both positions and their source citations
        rather than silently replacing a prior claim. Raw sources never enter the prompt digest.
        """

    private enum LifecycleOperation: String {
        case ingest
        case query
        case lint
    }

    private struct ParsedLinks: Sendable {
        let links: Set<String>
        let malformed: [String]
    }

    private let root: URL
    private let raw: WikiMemoryStore
    private let wiki: WikiMemoryStore

    public init(root: URL) {
        self.root = root
        raw = WikiMemoryStore(root: root, globalDirectoryName: "raw")
        wiki = WikiMemoryStore(root: root, globalDirectoryName: "wiki")
    }

    public nonisolated func rawDirectoryURL(for scope: MemoryScope) -> URL {
        raw.directoryURL(for: scope)
    }

    public nonisolated func wikiDirectoryURL(for scope: MemoryScope) -> URL {
        wiki.directoryURL(for: scope)
    }

    /// Captures one source exactly once. Raw documents are never overwritten or deleted by this
    /// API; the returned source ID can be cited from a curated wiki page.
    @discardableResult
    public func ingest(
        title: String,
        content: String,
        context: MemoryContext,
        sourceID: UUID = UUID()
    ) async throws -> MemoryEntryID {
        let trimmedTitle = title.trimmingCharacters(in: .whitespacesAndNewlines)
        let trimmedContent = content.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedTitle.isEmpty, !trimmedContent.isEmpty else {
            throw LocalStoreError.invalidData(path: "raw", reason: "source title and content are required")
        }
        try await prepareLifecycle(for: context)
        let name = "source-\(sourceID.uuidString.lowercased())"
        let summary = String(trimmedTitle.prefix(WikiMemoryStore.maximumDescriptionBytes))
        try preflightLogAppend(operation: .ingest, detail: "raw:\(name)")
        let stored = try await raw.write(
            MemoryNote(name: name, description: summary, body: trimmedContent),
            scope: context.defaultWriteScope,
            condition: .ifAbsent)
        try appendLog(operation: .ingest, detail: "raw:\(stored.note.name)")
        return MemoryEntryID(rawValue: "raw:\(stored.note.name)")
    }

    public func promptSnapshot(for context: MemoryContext) async throws -> MemoryPromptSnapshot {
        try await validateLifecycleForRead(context: context)
        return try await wiki.promptSnapshot(for: context)
    }

    /// Lists raw source documents without mixing them into the curated browser or prompt digest.
    public func sourceEntries(for context: MemoryContext) async throws -> [MemoryBrowserEntry] {
        try await validateLifecycleForRead(context: context)
        return try await raw.browserEntries(for: context).map { entry in
            guard let name = Self.name(from: entry.id) else {
                throw MemoryStoreError.invalidEntryID(entry.id.rawValue)
            }
            return MemoryBrowserEntry(
                id: MemoryEntryID(rawValue: "raw:\(name)"),
                title: MemoryBrowserEntry.displayTitle(for: entry.summary),
                summary: entry.summary,
                scope: entry.scope,
                modifiedAt: entry.modifiedAt,
                revision: entry.revision,
                canEdit: false,
                canDelete: false)
        }
    }

    /// Reads the finite curated page set and raw-source catalogue for a graph. It does not parse
    /// links or perform layout: both remain presentation work and run off the application's main
    /// actor. Raw sources are returned only as metadata; their body never enters the graph.
    public func graphMaterial(for context: MemoryContext) async throws -> LLMWikiGraphMaterial {
        try await validateLifecycleForRead(context: context)
        let allPageEntries = try await wiki.browserEntries(for: context)
        let allSources = try await sourceEntries(for: context)
        let pageEntries = Array(allPageEntries.prefix(Self.maximumGraphPages))
        let sources = Array(allSources.prefix(Self.maximumGraphSources))
        var isTruncated = allPageEntries.count > pageEntries.count || allSources.count > sources.count
        var pages: [LLMWikiGraphPage] = []
        pages.reserveCapacity(pageEntries.count)
        for entry in pageEntries {
            guard let name = Self.name(from: entry.id) else {
                throw MemoryStoreError.invalidEntryID(entry.id.rawValue)
            }
            let document = try await wiki.browserDocument(entry.id, context: context)
            let content = document.content.utf8
            if content.count > Self.maximumGraphPageContentBytes { isTruncated = true }
            pages.append(
                LLMWikiGraphPage(
                    entry: entry,
                    name: name,
                    content: String(
                        decoding: content.prefix(Self.maximumGraphPageContentBytes),
                        as: UTF8.self)))
        }
        return LLMWikiGraphMaterial(
            pages: pages,
            sources: try sources.map { entry in
                guard let name = Self.name(from: entry.id) else {
                    throw MemoryStoreError.invalidEntryID(entry.id.rawValue)
                }
                return LLMWikiGraphSource(entry: entry, name: name)
            },
            isTruncated: isTruncated)
    }

    public func sourceDocument(
        _ id: MemoryEntryID,
        context: MemoryContext
    ) async throws -> MemoryBrowserDocument {
        try await validateLifecycleForRead(context: context)
        let components = id.rawValue.split(separator: ":", maxSplits: 1, omittingEmptySubsequences: false)
        guard components.count == 2, components[0] == "raw" else {
            throw MemoryStoreError.invalidEntryID(id.rawValue)
        }
        let name = String(components[1])
        do {
            try WikiMemoryCodec.validateName(name)
        } catch {
            throw MemoryStoreError.invalidEntryID(id.rawValue)
        }
        let rawID = Self.entryID(name: name, scope: context.defaultWriteScope)
        let document = try await raw.browserDocument(rawID, context: context)
        return MemoryBrowserDocument(
            entry: MemoryBrowserEntry(
                id: id,
                title: MemoryBrowserEntry.displayTitle(for: document.entry.summary),
                summary: document.entry.summary,
                scope: document.entry.scope,
                modifiedAt: document.entry.modifiedAt,
                revision: document.entry.revision,
                canEdit: false,
                canDelete: false),
            content: document.content)
    }

    /// Bounded index-first lookup over curated page metadata. This deliberately does not read
    /// raw sources or perform embedding retrieval; callers can read a selected page afterward.
    public func query(
        _ query: String,
        context: MemoryContext
    ) async throws -> [MemoryBrowserEntry] {
        let needle = query.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !needle.isEmpty, needle.count <= Self.maximumQueryCharacters else {
            throw LocalStoreError.invalidData(
                path: "wiki",
                reason: "query must contain 1…\(Self.maximumQueryCharacters) characters")
        }
        try await prepareLifecycle(for: context)
        let entries = try await wiki.browserEntries(for: context)
        let indexData = try requiredLifecycleData(named: Self.indexFileName)
        let names = try Self.indexedNames(from: indexData)
        let entriesByName = Dictionary(
            uniqueKeysWithValues: entries.compactMap { entry in
                Self.name(from: entry.id).map { ($0, entry) }
            })
        let foldedNeedle = needle.folding(options: [.caseInsensitive, .diacriticInsensitive], locale: .current)
        let matches = names.compactMap { entriesByName[$0] }
            .filter { entry in
                let haystack = "\(entry.title) \(entry.summary)"
                    .folding(options: [.caseInsensitive, .diacriticInsensitive], locale: .current)
                return haystack.contains(foldedNeedle)
            }
        try preflightLogAppend(operation: .query, detail: "pages:\(matches.count)")
        try appendLog(operation: .query, detail: "pages:\(matches.count)")
        return Array(matches.prefix(Self.maximumQueryResults))
    }

    /// Deterministic structural health check. It never edits pages: the LLM decides how to repair
    /// a reported orphan or missing source citation through normal curated-page writes.
    public func lint(for context: MemoryContext) async throws -> LLMWikiLintReport {
        let pages = try await wiki.browserEntries(for: context)
        let rawEntries = try await raw.browserEntries(for: context)
        let pageNames = Set(pages.compactMap { Self.name(from: $0.id) })
        let sourceNames = Set(rawEntries.compactMap { Self.name(from: $0.id) })
        var inboundPages = Set<String>()
        var citedSources = Set<String>()
        var pagesMissingSourceCitations: [String] = []
        var invalidWikiLinks: [String] = []

        for page in pages {
            guard let pageName = Self.name(from: page.id) else {
                throw MemoryStoreError.invalidEntryID(page.id.rawValue)
            }
            let document = try await wiki.browserDocument(page.id, context: context)
            let parsed = Self.wikiLinks(in: document.content)
            var pageCitesSource = false
            for link in parsed.links {
                if pageNames.contains(link) {
                    inboundPages.insert(link)
                } else if sourceNames.contains(link) {
                    pageCitesSource = true
                    citedSources.insert(link)
                } else {
                    invalidWikiLinks.append("\(pageName): [[\(link)]]")
                }
            }
            invalidWikiLinks.append(contentsOf: parsed.malformed.map { "\(pageName): \($0)" })
            if !pageCitesSource { pagesMissingSourceCitations.append(pageName) }
        }

        let expectedIndex = try Self.indexData(for: pages)
        let rootExists = try LocalFileStore.directoryExists(at: root)
        let schemaData = try lifecycleDataIfPresent(named: Self.agentsFileName)
        let indexData = try lifecycleDataIfPresent(named: Self.indexFileName)
        let logData = try lifecycleDataIfPresent(named: Self.logFileName)
        var missingAuthorities: [String] = []
        if !rootExists { missingAuthorities.append("root/") }
        if !(try LocalFileStore.directoryExists(at: raw.directoryURL(for: context.defaultWriteScope))) {
            missingAuthorities.append("raw/")
        }
        if !(try LocalFileStore.directoryExists(at: wiki.directoryURL(for: context.defaultWriteScope))) {
            missingAuthorities.append("wiki/")
        }
        if schemaData == nil { missingAuthorities.append(Self.agentsFileName) }
        if indexData == nil { missingAuthorities.append(Self.indexFileName) }
        if logData == nil { missingAuthorities.append(Self.logFileName) }
        let malformedLogRecords = (try? Self.malformedLogRecordLines(in: logData ?? Data())) ?? [0]
        let report = LLMWikiLintReport(
            pageCount: pages.count,
            sourceCount: rawEntries.count,
            orphanPages: pageNames.subtracting(inboundPages).sorted(),
            pagesMissingSourceCitations: pagesMissingSourceCitations.sorted(),
            uncitedSources: sourceNames.subtracting(citedSources).sorted(),
            invalidWikiLinks: invalidWikiLinks.sorted(),
            malformedLogRecords: malformedLogRecords,
            missingAuthorities: missingAuthorities,
            schemaIsValid: schemaData == Data(Self.agentsContents.utf8),
            indexIsFresh: indexData == expectedIndex)

        // A broken log must be preserved for manual recovery. When it remains valid, lint itself
        // is part of the append-only chronology, including a compact health result.
        if report.malformedLogRecords.isEmpty, report.missingAuthorities.isEmpty {
            try preflightLogAppend(
                operation: .lint,
                detail: report.isHealthy ? "healthy" : "issues")
            try appendLog(operation: .lint, detail: report.isHealthy ? "healthy" : "issues")
        }
        return report
    }

    public func browserEntries(for context: MemoryContext) async throws -> [MemoryBrowserEntry] {
        try await validateLifecycleForRead(context: context)
        return try await wiki.browserEntries(for: context)
    }

    public func browserDocument(
        _ id: MemoryEntryID,
        context: MemoryContext
    ) async throws -> MemoryBrowserDocument {
        try await validateLifecycleForRead(context: context)
        return try await wiki.browserDocument(id, context: context)
    }

    public func remember(_ request: MemoryRememberRequest) async throws -> MemoryRememberReceipt {
        let sourceName = "source-\(request.idempotencyKey.uuidString.lowercased())"
        let source = MemoryNote(
            name: sourceName,
            description: String(request.title.prefix(WikiMemoryStore.maximumDescriptionBytes)),
            body: request.content.trimmingCharacters(in: .whitespacesAndNewlines))
        do {
            _ = try await ingest(
                title: request.title,
                content: request.content,
                context: request.context,
                sourceID: request.idempotencyKey)
        } catch let error as MemoryStoreError {
            guard case .conflict = error,
                try await raw.read(sourceName, scope: request.context.defaultWriteScope)?.note == source
            else { throw error }
        }

        var body = request.content
        while body.unicodeScalars.last?.value == 10 { body.unicodeScalars.removeLast() }
        let note = MemoryNote(
            name: request.suggestedName ?? "memory-\(request.idempotencyKey.uuidString.lowercased())",
            description: request.summary,
            body: body)
        do {
            let stored = try await write(note, scope: request.context.defaultWriteScope, condition: .ifAbsent)
            return try await receipt(for: stored, context: request.context, created: true)
        } catch let error as MemoryStoreError {
            guard case .conflict = error,
                let existing = try await wiki.read(note.name, scope: request.context.defaultWriteScope),
                existing.note == note
            else { throw error }
            return try await receipt(for: existing, context: request.context, created: false)
        }
    }

    public func summaries(in scope: MemoryScope) async throws -> [MemoryNoteSummary] {
        try await validateLifecycleForRead(context: Self.context(for: scope))
        return try await wiki.summaries(in: scope)
    }

    public func read(_ name: String, scope: MemoryScope) async throws -> StoredMemoryNote? {
        try await validateLifecycleForRead(context: Self.context(for: scope))
        return try await wiki.read(name, scope: scope)
    }

    public func write(
        _ note: MemoryNote,
        scope: MemoryScope,
        condition: MemoryWriteCondition
    ) async throws -> StoredMemoryNote {
        let context = Self.context(for: scope)
        try await prepareLifecycle(for: context)
        let stored = try await wiki.write(note, scope: scope, condition: condition)
        try await refreshIndex(for: context)
        return stored
    }

    @discardableResult
    public func delete(
        _ name: String,
        scope: MemoryScope,
        ifRevision revision: MemoryRevision? = nil
    ) async throws -> Bool {
        let context = Self.context(for: scope)
        try await prepareLifecycle(for: context)
        let deleted = try await wiki.delete(name, scope: scope, ifRevision: revision)
        if deleted { try await refreshIndex(for: context) }
        return deleted
    }

    private func prepareLifecycle(for context: MemoryContext) async throws {
        try LocalFileStore.ensureDirectory(at: root)
        try LocalFileStore.ensureDirectory(at: raw.directoryURL(for: context.defaultWriteScope))
        try LocalFileStore.ensureDirectory(at: wiki.directoryURL(for: context.defaultWriteScope))
        try ensureLifecycleFile(named: Self.agentsFileName, expected: Data(Self.agentsContents.utf8))
        try ensureLifecycleLog()
        try await refreshIndex(for: context)
        _ = try Self.malformedLogRecordLines(in: requiredLifecycleData(named: Self.logFileName))
    }

    private func validateLifecycleForRead(context: MemoryContext) async throws {
        guard try LocalFileStore.directoryExists(at: root) else { return }
        let pages = try await wiki.browserEntries(for: context)
        let expectedIndex = try Self.indexData(for: pages)
        try requireLifecycleFile(named: Self.agentsFileName, expected: Data(Self.agentsContents.utf8))
        try requireLifecycleFile(named: Self.indexFileName, expected: expectedIndex)
        let log = try requiredLifecycleData(named: Self.logFileName)
        _ = try Self.malformedLogRecordLines(in: log)
    }

    private func refreshIndex(for context: MemoryContext) async throws {
        let expected = try Self.indexData(for: try await wiki.browserEntries(for: context))
        let current = try lifecycleDataIfPresent(named: Self.indexFileName)
        if current != expected { try LocalFileStore.write(expected, to: lifecycleURL(named: Self.indexFileName)) }
    }

    private func ensureLifecycleFile(named name: String, expected: Data) throws {
        let url = lifecycleURL(named: name)
        if let current = try LocalFileStore.dataIfPresent(at: url) {
            guard current == expected else {
                throw LocalStoreError.invalidData(
                    path: url.path,
                    reason: "provider authority differs from GOAT's required canonical content")
            }
            return
        }
        try LocalFileStore.write(expected, to: url)
    }

    private func requireLifecycleFile(named name: String, expected: Data) throws {
        let url = lifecycleURL(named: name)
        guard let current = try LocalFileStore.dataIfPresent(at: url) else {
            throw LocalStoreError.invalidData(path: url.path, reason: "required provider authority is missing")
        }
        guard current == expected else {
            throw LocalStoreError.invalidData(
                path: url.path,
                reason: "provider authority is stale or has been edited outside GOAT")
        }
    }

    private func ensureLifecycleLog() throws {
        let url = lifecycleURL(named: Self.logFileName)
        if let current = try lifecycleDataIfPresent(named: Self.logFileName) {
            _ = try Self.malformedLogRecordLines(in: current)
            return
        }
        try LocalFileStore.write(Data(Self.logHeader.utf8), to: url)
    }

    private func lifecycleDataIfPresent(named name: String) throws -> Data? {
        try LocalFileStore.boundedDataIfPresent(
            at: lifecycleURL(named: name), maximumBytes: Self.maximumLifecycleLogBytes)
    }

    private func requiredLifecycleData(named name: String) throws -> Data {
        let url = lifecycleURL(named: name)
        guard let data = try lifecycleDataIfPresent(named: name) else {
            throw LocalStoreError.invalidData(path: url.path, reason: "required provider authority is missing")
        }
        return data
    }

    private func lifecycleURL(named name: String) -> URL {
        root.appendingPathComponent(name, isDirectory: false)
    }

    private func preflightLogAppend(operation: LifecycleOperation, detail: String) throws {
        let log = try requiredLifecycleData(named: Self.logFileName)
        _ = try Self.malformedLogRecordLines(in: log)
        let next = Self.logLine(operation: operation, detail: detail)
        guard log.count + next.utf8.count <= Self.maximumLifecycleLogBytes else {
            throw MemoryStoreError.capacityExceeded(
                path: lifecycleURL(named: Self.logFileName).path,
                reason: "LLM Wiki log exceeds \(Self.maximumLifecycleLogBytes) bytes")
        }
    }

    private func appendLog(operation: LifecycleOperation, detail: String) throws {
        let log = try requiredLifecycleData(named: Self.logFileName)
        let line = Self.logLine(operation: operation, detail: detail)
        guard log.count + line.utf8.count <= Self.maximumLifecycleLogBytes else {
            throw MemoryStoreError.capacityExceeded(
                path: lifecycleURL(named: Self.logFileName).path,
                reason: "LLM Wiki log exceeds \(Self.maximumLifecycleLogBytes) bytes")
        }
        var next = log
        next.append(contentsOf: line.utf8)
        try LocalFileStore.write(next, to: lifecycleURL(named: Self.logFileName))
    }

    private func receipt(
        for stored: StoredMemoryNote,
        context: MemoryContext,
        created: Bool
    ) async throws -> MemoryRememberReceipt {
        let entry = try await wiki.browserEntries(for: context).first {
            $0.title == stored.note.name
        }
        guard let entry else {
            throw LocalStoreError.operationFailed(
                path: stored.note.name,
                operation: "address LLM Wiki memory note",
                reason: "stored note was not found in the curated index")
        }
        return MemoryRememberReceipt(
            status: .stored,
            entryID: entry.id,
            revision: stored.revision,
            undoToken: created ? MemoryUndoToken(entryID: entry.id, revision: stored.revision) : nil)
    }

    private nonisolated static func logLine(operation: LifecycleOperation, detail: String) -> String {
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime]
        return "- \(formatter.string(from: Date())) | \(operation.rawValue) | \(detail)\n"
    }

    private nonisolated static func malformedLogRecordLines(in data: Data) throws -> [Int] {
        guard let text = String(data: data, encoding: .utf8) else {
            throw LocalStoreError.invalidData(path: Self.logFileName, reason: "log is not valid UTF-8")
        }
        guard text.hasPrefix(Self.logHeader) else {
            throw LocalStoreError.invalidData(path: Self.logFileName, reason: "log header is not canonical")
        }
        let records = text.dropFirst(Self.logHeader.count).split(separator: "\n", omittingEmptySubsequences: false)
        var malformed: [Int] = []
        for (offset, record) in records.enumerated() {
            guard !record.isEmpty else { continue }
            let parts = record.split(separator: "|", omittingEmptySubsequences: false).map {
                $0.trimmingCharacters(in: .whitespaces)
            }
            let line = Self.logHeader.split(separator: "\n", omittingEmptySubsequences: false).count + offset
            guard parts.count == 3,
                record.hasPrefix("- "),
                ISO8601DateFormatter().date(from: String(parts[0].dropFirst(2))) != nil,
                LifecycleOperation(rawValue: String(parts[1])) != nil,
                !parts[2].isEmpty,
                parts[2].utf8.count <= 512,
                !parts[2].contains("\n")
            else {
                malformed.append(line)
                continue
            }
            if parts[1] == LifecycleOperation.ingest.rawValue {
                let source = String(parts[2])
                guard source.hasPrefix("raw:"), (try? WikiMemoryCodec.validateName(String(source.dropFirst(4)))) != nil
                else {
                    malformed.append(line)
                    continue
                }
            }
        }
        return malformed
    }

    private nonisolated static func indexData(for entries: [MemoryBrowserEntry]) throws -> Data {
        var value = Self.indexHeader
        for entry in entries {
            guard let name = Self.name(from: entry.id) else {
                throw MemoryStoreError.invalidEntryID(entry.id.rawValue)
            }
            value += "- [[\(name)]]: \(entry.summary)\n"
        }
        let data = Data(value.utf8)
        guard data.count <= WikiMemoryStore.maximumIndexBytes else {
            throw MemoryStoreError.capacityExceeded(
                path: Self.indexFileName,
                reason: "LLM Wiki index exceeds \(WikiMemoryStore.maximumIndexBytes) bytes")
        }
        return data
    }

    private nonisolated static func indexedNames(from data: Data) throws -> [String] {
        guard let value = String(data: data, encoding: .utf8), value.hasPrefix(Self.indexHeader) else {
            throw LocalStoreError.invalidData(path: Self.indexFileName, reason: "index is not canonical")
        }
        var names: [String] = []
        for line in value.dropFirst(Self.indexHeader.count).split(separator: "\n") {
            guard line.hasPrefix("- [["), let delimiter = line.range(of: "]]: ") else {
                throw LocalStoreError.invalidData(path: Self.indexFileName, reason: "index entry is malformed")
            }
            let name = String(line[line.index(line.startIndex, offsetBy: 4)..<delimiter.lowerBound])
            try WikiMemoryCodec.validateName(name)
            names.append(name)
        }
        return names
    }

    private nonisolated static func context(for scope: MemoryScope) -> MemoryContext {
        switch scope {
        case .global: MemoryContext()
        case .project(let id): MemoryContext(projectID: id)
        }
    }

    private nonisolated static func entryID(name: String, scope: MemoryScope) -> MemoryEntryID {
        switch scope {
        case .global: MemoryEntryID(rawValue: "wiki:global:\(name)")
        case .project(let id): MemoryEntryID(rawValue: "wiki:project:\(id.uuidString):\(name)")
        }
    }

    private nonisolated static func name(from id: MemoryEntryID) -> String? {
        id.rawValue.split(separator: ":").last.map(String.init)
    }

    /// Scan Markdown conservatively. Fenced code blocks and inline code are intentionally opaque
    /// because `[[not-a-link]]` in code is not a knowledge relationship.
    private nonisolated static func wikiLinks(in content: String) -> ParsedLinks {
        var links = Set<String>()
        var malformed: [String] = []
        var inFence = false
        for rawLine in content.split(separator: "\n", omittingEmptySubsequences: false) {
            let line = String(rawLine)
            if line.trimmingCharacters(in: .whitespaces).hasPrefix("```") {
                inFence.toggle()
                continue
            }
            guard !inFence else { continue }
            let visible = Self.removingInlineCode(from: line)
            var remainder = visible[...]
            while let start = remainder.range(of: "[[") {
                guard let end = remainder[start.upperBound...].range(of: "]]"), start.upperBound < end.lowerBound else {
                    malformed.append("unterminated wikilink")
                    break
                }
                let candidate = String(remainder[start.upperBound..<end.lowerBound])
                do {
                    try WikiMemoryCodec.validateName(candidate)
                    links.insert(candidate)
                } catch {
                    malformed.append("invalid wikilink [[\(candidate)]]")
                }
                remainder = remainder[end.upperBound...]
            }
        }
        if inFence { malformed.append("unterminated fenced code block") }
        return ParsedLinks(links: links, malformed: malformed)
    }

    private nonisolated static func removingInlineCode(from line: String) -> String {
        var output = ""
        var inCode = false
        for character in line {
            if character == "`" {
                inCode.toggle()
                continue
            }
            if !inCode { output.append(character) }
        }
        return output
    }
}
