import Foundation

enum WikiMemoryCodec {
    static let indexHeader = """
        # Memory

        > Generated by GOAT from note frontmatter. Edit the notes, not this index.

        """

    static func validateName(_ name: String) throws {
        guard name != "memory", !name.isEmpty, name.utf8.count <= 64 else {
            throw MemoryStoreError.invalidName(name)
        }
        let scalars = Array(name.unicodeScalars)
        guard scalars.first.map(isLowercaseLetterOrDigit) == true,
            scalars.last.map(isLowercaseLetterOrDigit) == true,
            scalars.allSatisfy({ isLowercaseLetterOrDigit($0) || $0.value == 45 })
        else {
            throw MemoryStoreError.invalidName(name)
        }
    }

    static func validate(_ note: MemoryNote, path: String) throws {
        try validateName(note.name)
        try validateDescription(note.description, path: path)
        guard !note.body.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw MemoryStoreError.invalidNote(path: path, reason: "body cannot be empty")
        }
        guard !note.body.unicodeScalars.contains(where: { $0.value == 0 }) else {
            throw MemoryStoreError.invalidNote(path: path, reason: "body contains a NUL character")
        }
        guard !note.body.unicodeScalars.contains(where: { $0.value == 13 }) else {
            throw MemoryStoreError.invalidNote(path: path, reason: "body contains a carriage return")
        }
        guard note.body.unicodeScalars.last?.value != 10 else {
            throw MemoryStoreError.invalidNote(
                path: path,
                reason: "body must not contain trailing line feeds")
        }
    }

    static func encode(_ note: MemoryNote, path: String) throws -> Data {
        try validate(note, path: path)
        let encodedName = try encodeJSONString(note.name, path: path)
        let encodedDescription = try encodeJSONString(note.description, path: path)
        var value = """
            ---
            name: \(encodedName)
            description: \(encodedDescription)
            ---

            \(note.body)
            """
        if !value.hasSuffix("\n") { value.append("\n") }
        let data = Data(value.utf8)
        guard data.count <= WikiMemoryStore.maximumNoteBytes else {
            throw MemoryStoreError.capacityExceeded(
                path: path,
                reason: "note exceeds \(WikiMemoryStore.maximumNoteBytes) bytes")
        }
        return data
    }

    static func decode(_ data: Data, expectedName: String, path: String) throws -> MemoryNote {
        guard data.count <= WikiMemoryStore.maximumNoteBytes else {
            throw MemoryStoreError.capacityExceeded(
                path: path,
                reason: "note exceeds \(WikiMemoryStore.maximumNoteBytes) bytes")
        }
        guard let source = String(data: data, encoding: .utf8) else {
            throw MemoryStoreError.invalidNote(path: path, reason: "note is not valid UTF-8")
        }
        guard !source.unicodeScalars.contains(where: { $0.value == 13 }) else {
            throw MemoryStoreError.invalidNote(path: path, reason: "note contains a carriage return")
        }
        guard source.hasPrefix("---\n"),
            let close = source.range(
                of: "\n---\n", range: source.index(source.startIndex, offsetBy: 4)..<source.endIndex)
        else {
            throw MemoryStoreError.invalidNote(path: path, reason: "frontmatter delimiters are missing")
        }

        let headerStart = source.index(source.startIndex, offsetBy: 4)
        let header = String(source[headerStart..<close.lowerBound])
        let lines = header.split(separator: "\n", omittingEmptySubsequences: false).map(String.init)
        guard lines.count == 2,
            lines[0].hasPrefix("name: "),
            lines[1].hasPrefix("description: ")
        else {
            throw MemoryStoreError.invalidNote(
                path: path,
                reason: "frontmatter must contain exactly name then description")
        }
        let name = try decodeJSONString(
            String(lines[0].dropFirst("name: ".count)), path: path, field: "name")
        let description = try decodeJSONString(
            String(lines[1].dropFirst("description: ".count)), path: path, field: "description")
        guard name == expectedName else {
            throw MemoryStoreError.invalidNote(
                path: path, reason: "frontmatter name must match the filename")
        }

        var bodyStart = close.upperBound
        if bodyStart < source.endIndex, source[bodyStart] == "\n" {
            bodyStart = source.index(after: bodyStart)
        }
        var body = String(source[bodyStart...])
        if body.hasSuffix("\n") { body.removeLast() }
        let note = MemoryNote(name: name, description: description, body: body)
        try validate(note, path: path)
        return note
    }

    static func indexData(for summaries: [MemoryNoteSummary], path: String) throws -> Data {
        var value = indexHeader
        for summary in summaries {
            value += "- [[\(summary.name)]]: \(summary.description)\n"
        }
        let data = Data(value.utf8)
        guard data.count <= WikiMemoryStore.maximumIndexBytes else {
            throw MemoryStoreError.capacityExceeded(
                path: path,
                reason: "index exceeds \(WikiMemoryStore.maximumIndexBytes) bytes")
        }
        return data
    }

    /// Only indexes with GOAT's exact header are repairable derived state. Arbitrary text,
    /// invalid UTF-8, and unsafe filesystem entries remain untouched for manual recovery.
    static func validateRepairableIndex(_ data: Data, path: String) throws {
        guard data.count <= WikiMemoryStore.maximumIndexBytes else {
            throw MemoryStoreError.capacityExceeded(
                path: path,
                reason: "index exceeds \(WikiMemoryStore.maximumIndexBytes) bytes")
        }
        guard let value = String(data: data, encoding: .utf8) else {
            throw MemoryStoreError.invalidNote(path: path, reason: "index is not valid UTF-8")
        }
        guard value.hasPrefix(indexHeader) else {
            throw MemoryStoreError.invalidNote(
                path: path, reason: "index does not have GOAT's generated header")
        }
        let remainder = value.dropFirst(indexHeader.count)
        guard remainder.isEmpty || remainder.hasSuffix("\n") else {
            throw MemoryStoreError.invalidNote(
                path: path, reason: "index entries must end with a newline")
        }
        var lines = remainder.split(separator: "\n", omittingEmptySubsequences: false)
        if !lines.isEmpty { lines.removeLast() }
        var seen: Set<String> = []
        for line in lines {
            guard !line.isEmpty else {
                throw MemoryStoreError.invalidNote(
                    path: path, reason: "index contains an empty entry")
            }
            guard line.hasPrefix("- [["), let close = line.range(of: "]]: ") else {
                throw MemoryStoreError.invalidNote(path: path, reason: "index contains an invalid entry")
            }
            let nameStart = line.index(line.startIndex, offsetBy: 4)
            let name = String(line[nameStart..<close.lowerBound])
            do {
                try validateName(name)
            } catch {
                throw MemoryStoreError.invalidNote(path: path, reason: "index contains an invalid note name")
            }
            let description = String(line[close.upperBound...])
            do {
                try validateDescription(description, path: path)
            } catch {
                throw MemoryStoreError.invalidNote(
                    path: path, reason: "index contains an invalid description")
            }
            guard line == Substring("- [[\(name)]]: \(description)") else {
                throw MemoryStoreError.invalidNote(
                    path: path, reason: "index contains a noncanonical entry")
            }
            guard seen.insert(name).inserted else {
                throw MemoryStoreError.invalidNote(path: path, reason: "index contains a duplicate note")
            }
        }
    }

    private static func isLowercaseLetterOrDigit(_ scalar: UnicodeScalar) -> Bool {
        (97...122).contains(scalar.value) || (48...57).contains(scalar.value)
    }

    private static func isDisallowedFrontmatterScalar(_ scalar: UnicodeScalar) -> Bool {
        scalar.properties.isWhitespace && scalar.value != 32
            || scalar.value < 32
            || scalar.value == 127
    }

    private static func validateDescription(_ description: String, path: String) throws {
        let descriptionBytes = description.utf8.count
        guard !description.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw MemoryStoreError.invalidNote(path: path, reason: "description cannot be empty")
        }
        guard descriptionBytes <= WikiMemoryStore.maximumDescriptionBytes else {
            throw MemoryStoreError.capacityExceeded(
                path: path,
                reason: "description exceeds \(WikiMemoryStore.maximumDescriptionBytes) UTF-8 bytes")
        }
        guard !description.unicodeScalars.contains(where: isDisallowedFrontmatterScalar) else {
            throw MemoryStoreError.invalidNote(
                path: path, reason: "description must be one printable line")
        }
    }

    private static func encodeJSONString(_ value: String, path: String) throws -> String {
        do {
            let data = try JSONEncoder().encode(value)
            guard let encoded = String(data: data, encoding: .utf8) else {
                throw MemoryStoreError.invalidNote(path: path, reason: "frontmatter could not be encoded")
            }
            return encoded
        } catch let error as MemoryStoreError {
            throw error
        } catch {
            throw MemoryStoreError.invalidNote(
                path: path, reason: "frontmatter could not be encoded: \(error.localizedDescription)")
        }
    }

    private static func decodeJSONString(
        _ value: String,
        path: String,
        field: String
    ) throws -> String {
        do {
            return try JSONDecoder().decode(String.self, from: Data(value.utf8))
        } catch {
            throw MemoryStoreError.invalidNote(
                path: path, reason: "\(field) must be a JSON-quoted YAML string")
        }
    }
}
