import Caprine
import Foundation
import SwiftUI

/// Structured representation of a file change generated by a tool call.
struct ToolFileDiff: Equatable, Sendable {
    enum ChangeKind: Equatable, Sendable {
        case edit
        case create
    }

    struct DiffLine: Identifiable, Equatable, Sendable {
        var id: Int
        enum Kind: Equatable, Sendable {
            case context
            case addition
            case deletion
        }
        let kind: Kind
        let text: String
        let oldLineNumber: Int?
        let newLineNumber: Int?
    }

    let path: String
    let kind: ChangeKind
    let additionsCount: Int
    let deletionsCount: Int
    let lines: [DiffLine]
    let isTruncated: Bool
    let totalLinesCount: Int

    init(
        path: String,
        kind: ChangeKind,
        additionsCount: Int,
        deletionsCount: Int,
        lines: [DiffLine],
        isTruncated: Bool = false,
        totalLinesCount: Int? = nil
    ) {
        self.path = path
        self.kind = kind
        self.additionsCount = additionsCount
        self.deletionsCount = deletionsCount
        self.lines = lines
        self.isTruncated = isTruncated
        self.totalLinesCount = totalLinesCount ?? lines.count
    }
}

/// Parses tool invocation arguments into a structured file diff.
@MainActor enum ToolDiffParser {
    public static let maxDiffLines = 500
    public static let maxLCSDimension = 500

    private static let cache = NSCache<NSString, DiffCacheEntry>()

    private final class DiffCacheEntry: @unchecked Sendable {
        let arguments: String
        let diff: ToolFileDiff?
        init(arguments: String, diff: ToolFileDiff?) {
            self.arguments = arguments
            self.diff = diff
        }
    }

    static func parse(tool: String, arguments: String) -> ToolFileDiff? {
        guard tool == "pen_edit_file" || tool == "pen_write_file" else { return nil }
        guard arguments.utf8.count <= 131_072 else { return nil }

        let cacheKey = "\(tool):\(arguments.hashValue):\(arguments.count)" as NSString
        if let entry = cache.object(forKey: cacheKey), entry.arguments == arguments {
            return entry.diff
        }

        let parsed = parseUncached(tool: tool, arguments: arguments)
        cache.setObject(DiffCacheEntry(arguments: arguments, diff: parsed), forKey: cacheKey)
        return parsed
    }

    private static func parseUncached(tool: String, arguments: String) -> ToolFileDiff? {
        guard let data = arguments.data(using: .utf8),
            let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
            let path = json["path"] as? String, !path.isEmpty
        else { return nil }

        if tool == "pen_edit_file" {
            guard let oldText = json["old_text"] as? String,
                let newText = json["new_text"] as? String
            else { return nil }
            return diffBetween(path: path, oldText: oldText, newText: newText)
        } else {
            guard let content = json["content"] as? String else { return nil }
            return diffForCreation(path: path, content: content)
        }
    }

    private static func diffForCreation(path: String, content: String) -> ToolFileDiff {
        let rawLines = content.components(separatedBy: "\n")
        let totalCount = rawLines.count
        let isTruncated = totalCount > maxDiffLines
        let slice = isTruncated ? Array(rawLines.prefix(maxDiffLines)) : rawLines
        var lines: [ToolFileDiff.DiffLine] = []
        lines.reserveCapacity(slice.count)
        for (index, line) in slice.enumerated() {
            lines.append(
                ToolFileDiff.DiffLine(
                    id: index,
                    kind: .addition,
                    text: line,
                    oldLineNumber: nil,
                    newLineNumber: index + 1
                ))
        }
        return ToolFileDiff(
            path: path,
            kind: .create,
            additionsCount: totalCount,
            deletionsCount: 0,
            lines: lines,
            isTruncated: isTruncated,
            totalLinesCount: totalCount
        )
    }

    private static func diffBetween(path: String, oldText: String, newText: String) -> ToolFileDiff {
        let oldLines = oldText.components(separatedBy: "\n")
        let newLines = newText.components(separatedBy: "\n")

        let m = oldLines.count
        let n = newLines.count

        // Guard against runaway LCS on exceptionally large text blocks
        if m > maxLCSDimension || n > maxLCSDimension {
            var lines: [ToolFileDiff.DiffLine] = []
            let total = m + n
            let isTruncated = total > maxDiffLines
            var id = 0
            for (idx, line) in oldLines.enumerated() {
                if id >= maxDiffLines { break }
                lines.append(
                    ToolFileDiff.DiffLine(
                        id: id, kind: .deletion, text: line, oldLineNumber: idx + 1, newLineNumber: nil))
                id += 1
            }
            if id < maxDiffLines {
                for (idx, line) in newLines.enumerated() {
                    if id >= maxDiffLines { break }
                    lines.append(
                        ToolFileDiff.DiffLine(
                            id: id, kind: .addition, text: line, oldLineNumber: nil, newLineNumber: idx + 1))
                    id += 1
                }
            }
            return ToolFileDiff(
                path: path,
                kind: .edit,
                additionsCount: n,
                deletionsCount: m,
                lines: lines,
                isTruncated: isTruncated,
                totalLinesCount: total
            )
        }

        var dp: [[Int]] = Array(repeating: Array(repeating: 0, count: n + 1), count: m + 1)
        for i in 0..<m {
            for j in 0..<n {
                if oldLines[i] == newLines[j] {
                    dp[i + 1][j + 1] = dp[i][j] + 1
                } else {
                    let a = dp[i + 1][j]
                    let b = dp[i][j + 1]
                    dp[i + 1][j + 1] = a > b ? a : b
                }
            }
        }

        var i = m
        var j = n
        var temp: [ToolFileDiff.DiffLine] = []
        var additions = 0
        var deletions = 0

        while i > 0 || j > 0 {
            if i > 0 && j > 0 && oldLines[i - 1] == newLines[j - 1] {
                temp.append(
                    ToolFileDiff.DiffLine(
                        id: 0, kind: .context, text: oldLines[i - 1],
                        oldLineNumber: i, newLineNumber: j))
                i -= 1
                j -= 1
            } else if j > 0 && (i == 0 || dp[i][j - 1] >= dp[i - 1][j]) {
                temp.append(
                    ToolFileDiff.DiffLine(
                        id: 0, kind: .addition, text: newLines[j - 1],
                        oldLineNumber: nil, newLineNumber: j))
                additions += 1
                j -= 1
            } else if i > 0 && (j == 0 || dp[i][j - 1] < dp[i - 1][j]) {
                temp.append(
                    ToolFileDiff.DiffLine(
                        id: 0, kind: .deletion, text: oldLines[i - 1],
                        oldLineNumber: i, newLineNumber: nil))
                deletions += 1
                i -= 1
            }
        }

        temp.reverse()
        let totalCount = temp.count
        let isTruncated = totalCount > maxDiffLines
        let slice = isTruncated ? Array(temp.prefix(maxDiffLines)) : temp
        var finalLines: [ToolFileDiff.DiffLine] = []
        finalLines.reserveCapacity(slice.count)
        for (idx, var item) in slice.enumerated() {
            item.id = idx
            finalLines.append(item)
        }

        return ToolFileDiff(
            path: path,
            kind: .edit,
            additionsCount: additions,
            deletionsCount: deletions,
            lines: finalLines,
            isTruncated: isTruncated,
            totalLinesCount: totalCount
        )
    }
}

/// A clean, unified diff presentation view for tool operations (ADR-0094).
struct ToolDiffView: View {
    @Environment(AppModel.self) private var model
    let diff: ToolFileDiff
    let rawJSON: String
    var maxHeight: CGFloat = 220
    var allowsRawToggle: Bool = true

    @State private var showRaw = false

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            header
            if showRaw {
                JSONTreeView(raw: rawJSON)
                    .frame(maxWidth: .infinity, alignment: .leading)
            } else {
                diffContent
            }
        }
    }

    private var header: some View {
        HStack(spacing: 8) {
            Image(systemName: diff.kind == .create ? "doc.badge.plus" : "doc.text")
                .foregroundStyle(model.theme.tokens.muted)
                .font(Caprine.Activity.badgeFont)

            Text(diff.path)
                .font(Caprine.Activity.monospaceFont.weight(.semibold))
                .foregroundStyle(model.theme.tokens.ink)
                .lineLimit(1)
                .truncationMode(.middle)

            Spacer(minLength: 4)

            HStack(spacing: 6) {
                if diff.additionsCount > 0 {
                    Text("+\(diff.additionsCount)")
                        .font(Caprine.Activity.badgeFont.monospaced())
                        .foregroundStyle(Caprine.Semantic.success)
                }
                if diff.deletionsCount > 0 {
                    Text("-\(diff.deletionsCount)")
                        .font(Caprine.Activity.badgeFont.monospaced())
                        .foregroundStyle(Caprine.Semantic.danger)
                }
            }

            if allowsRawToggle {
                Button {
                    showRaw.toggle()
                } label: {
                    Image(systemName: showRaw ? "doc.text.magnifyingglass" : "curlybraces")
                        .font(Caprine.Activity.badgeFont)
                        .foregroundStyle(model.theme.tokens.muted)
                }
                .buttonStyle(.plain)
                .help(showRaw ? "Show unified diff" : "Show raw JSON payload")
                .accessibilityLabel(showRaw ? "Show unified diff" : "Show raw JSON payload")
            }
        }
        .padding(.horizontal, 6)
        .padding(.vertical, 4)
        .background(model.theme.tokens.surface.opacity(0.6), in: RoundedRectangle(cornerRadius: 6))
    }

    private var diffContent: some View {
        ScrollView([.horizontal, .vertical]) {
            VStack(alignment: .leading, spacing: 1) {
                ForEach(diff.lines) { line in
                    diffRow(line)
                }
                if diff.isTruncated {
                    truncationNotice
                }
            }
            .padding(.vertical, 4)
            .frame(maxWidth: .infinity, alignment: .leading)
        }
        .frame(maxHeight: maxHeight)
        .background(model.theme.tokens.surface.opacity(0.3), in: RoundedRectangle(cornerRadius: 6))
        .textSelection(.enabled)
    }

    private var truncationNotice: some View {
        HStack(spacing: 6) {
            Image(systemName: "ellipsis.circle")
            Text("Diff truncated to first \(diff.lines.count) of \(diff.totalLinesCount) lines.")
            if allowsRawToggle {
                Button("Show raw") {
                    showRaw = true
                }
                .buttonStyle(.plain)
                .foregroundStyle(model.theme.tokens.tint)
            }
        }
        .font(Caprine.Activity.badgeFont)
        .foregroundStyle(model.theme.tokens.muted)
        .padding(.horizontal, 6)
        .padding(.vertical, 4)
    }

    @ViewBuilder
    private func diffRow(_ line: ToolFileDiff.DiffLine) -> some View {
        HStack(alignment: .top, spacing: 4) {
            // Line numbers gutter
            HStack(spacing: 4) {
                Text(line.oldLineNumber.map { String($0) } ?? "")
                    .frame(width: 24, alignment: .trailing)
                Text(line.newLineNumber.map { String($0) } ?? "")
                    .frame(width: 24, alignment: .trailing)
            }
            .font(Caprine.Activity.badgeFont.monospaced())
            .foregroundStyle(model.theme.tokens.muted.opacity(0.7))

            // Prefix (+, -, space)
            Text(line.kind == .addition ? "+" : (line.kind == .deletion ? "-" : " "))
                .font(Caprine.Activity.monospaceFont.weight(.bold))
                .foregroundStyle(
                    line.kind == .addition
                        ? Caprine.Semantic.success
                        : (line.kind == .deletion ? Caprine.Semantic.danger : model.theme.tokens.muted)
                )
                .frame(width: 10, alignment: .center)

            // Content text
            Text(line.text.isEmpty ? " " : line.text)
                .font(Caprine.Activity.monospaceFont)
                .foregroundStyle(model.theme.tokens.ink)
                .frame(maxWidth: .infinity, alignment: .leading)
        }
        .padding(.horizontal, 6)
        .padding(.vertical, 1)
        .background(rowBackground(for: line.kind))
    }

    @ViewBuilder
    private func rowBackground(for kind: ToolFileDiff.DiffLine.Kind) -> some View {
        switch kind {
        case .addition:
            Caprine.Semantic.success.opacity(0.12)
        case .deletion:
            Caprine.Semantic.danger.opacity(0.12)
        case .context:
            Color.clear
        }
    }
}
