import Caprine
import Foundation
import SwiftUI

/// Structured representation of a file change generated by a tool call.
struct ToolFileDiff: Equatable, Sendable {
    enum ChangeKind: Equatable, Sendable {
        case edit
        case create
    }

    struct DiffLine: Identifiable, Equatable, Sendable {
        var id: Int
        enum Kind: Equatable, Sendable {
            case context
            case addition
            case deletion
        }
        let kind: Kind
        let text: String
        let oldLineNumber: Int?
        let newLineNumber: Int?
    }

    let path: String
    let kind: ChangeKind
    let additionsCount: Int
    let deletionsCount: Int
    let lines: [DiffLine]
}

/// Parses tool invocation arguments into a structured file diff.
enum ToolDiffParser {
    static func parse(tool: String, arguments: String) -> ToolFileDiff? {
        guard tool == "pen_edit_file" || tool == "pen_write_file" else { return nil }
        guard arguments.utf8.count <= 131_072,
            let data = arguments.data(using: .utf8),
            let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
            let path = json["path"] as? String, !path.isEmpty
        else { return nil }

        if tool == "pen_edit_file" {
            guard let oldText = json["old_text"] as? String,
                let newText = json["new_text"] as? String
            else { return nil }
            return diffBetween(path: path, oldText: oldText, newText: newText)
        } else {
            guard let content = json["content"] as? String else { return nil }
            return diffForCreation(path: path, content: content)
        }
    }

    private static func diffForCreation(path: String, content: String) -> ToolFileDiff {
        let rawLines = content.components(separatedBy: "\n")
        var lines: [ToolFileDiff.DiffLine] = []
        for (index, line) in rawLines.enumerated() {
            lines.append(
                ToolFileDiff.DiffLine(
                    id: index,
                    kind: .addition,
                    text: line,
                    oldLineNumber: nil,
                    newLineNumber: index + 1
                ))
        }
        return ToolFileDiff(
            path: path,
            kind: .create,
            additionsCount: lines.count,
            deletionsCount: 0,
            lines: lines
        )
    }

    private static func diffBetween(path: String, oldText: String, newText: String) -> ToolFileDiff {
        let oldLines = oldText.components(separatedBy: "\n")
        let newLines = newText.components(separatedBy: "\n")

        let m = oldLines.count
        let n = newLines.count

        // Guard against runaway LCS on exceptionally large text blocks
        if m > 500 || n > 500 {
            var lines: [ToolFileDiff.DiffLine] = []
            var id = 0
            for (idx, line) in oldLines.enumerated() {
                lines.append(
                    ToolFileDiff.DiffLine(
                        id: id, kind: .deletion, text: line, oldLineNumber: idx + 1, newLineNumber: nil))
                id += 1
            }
            for (idx, line) in newLines.enumerated() {
                lines.append(
                    ToolFileDiff.DiffLine(
                        id: id, kind: .addition, text: line, oldLineNumber: nil, newLineNumber: idx + 1))
                id += 1
            }
            return ToolFileDiff(
                path: path,
                kind: .edit,
                additionsCount: n,
                deletionsCount: m,
                lines: lines
            )
        }

        var dp: [[Int]] = Array(repeating: Array(repeating: 0, count: n + 1), count: m + 1)
        for i in 0..<m {
            for j in 0..<n {
                if oldLines[i] == newLines[j] {
                    dp[i + 1][j + 1] = dp[i][j] + 1
                } else {
                    let a = dp[i + 1][j]
                    let b = dp[i][j + 1]
                    dp[i + 1][j + 1] = a > b ? a : b
                }
            }
        }

        var i = m
        var j = n
        var temp: [ToolFileDiff.DiffLine] = []
        var additions = 0
        var deletions = 0

        while i > 0 || j > 0 {
            if i > 0 && j > 0 && oldLines[i - 1] == newLines[j - 1] {
                temp.append(
                    ToolFileDiff.DiffLine(
                        id: 0, kind: .context, text: oldLines[i - 1],
                        oldLineNumber: i, newLineNumber: j))
                i -= 1
                j -= 1
            } else if j > 0 && (i == 0 || dp[i][j - 1] >= dp[i - 1][j]) {
                temp.append(
                    ToolFileDiff.DiffLine(
                        id: 0, kind: .addition, text: newLines[j - 1],
                        oldLineNumber: nil, newLineNumber: j))
                additions += 1
                j -= 1
            } else if i > 0 && (j == 0 || dp[i][j - 1] < dp[i - 1][j]) {
                temp.append(
                    ToolFileDiff.DiffLine(
                        id: 0, kind: .deletion, text: oldLines[i - 1],
                        oldLineNumber: i, newLineNumber: nil))
                deletions += 1
                i -= 1
            }
        }

        temp.reverse()
        var finalLines: [ToolFileDiff.DiffLine] = []
        for (idx, var item) in temp.enumerated() {
            item.id = idx
            finalLines.append(item)
        }

        return ToolFileDiff(
            path: path,
            kind: .edit,
            additionsCount: additions,
            deletionsCount: deletions,
            lines: finalLines
        )
    }
}

/// A clean, unified diff presentation view for tool operations (ADR-0094).
struct ToolDiffView: View {
    @Environment(AppModel.self) private var model
    let diff: ToolFileDiff
    let rawJSON: String
    var maxHeight: CGFloat = 220
    var allowsRawToggle: Bool = true

    @State private var showRaw = false

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            header
            if showRaw {
                JSONTreeView(raw: rawJSON)
                    .frame(maxWidth: .infinity, alignment: .leading)
            } else {
                diffContent
            }
        }
    }

    private var header: some View {
        HStack(spacing: 8) {
            Image(systemName: diff.kind == .create ? "doc.badge.plus" : "doc.text")
                .foregroundStyle(model.theme.tokens.muted)
                .font(.system(size: 11))

            Text(diff.path)
                .font(.system(size: 11, weight: .semibold, design: .monospaced))
                .foregroundStyle(model.theme.tokens.ink)
                .lineLimit(1)
                .truncationMode(.middle)

            Spacer(minLength: 4)

            HStack(spacing: 6) {
                if diff.additionsCount > 0 {
                    Text("+\(diff.additionsCount)")
                        .font(.system(size: 10, weight: .bold, design: .monospaced))
                        .foregroundStyle(Caprine.Semantic.success)
                }
                if diff.deletionsCount > 0 {
                    Text("-\(diff.deletionsCount)")
                        .font(.system(size: 10, weight: .bold, design: .monospaced))
                        .foregroundStyle(Caprine.Semantic.danger)
                }
            }

            if allowsRawToggle {
                Button {
                    showRaw.toggle()
                } label: {
                    Image(systemName: showRaw ? "doc.text.magnifyingglass" : "curlybraces")
                        .font(.system(size: 10))
                        .foregroundStyle(model.theme.tokens.muted)
                }
                .buttonStyle(.plain)
                .help(showRaw ? "Show unified diff" : "Show raw JSON payload")
                .accessibilityLabel(showRaw ? "Show unified diff" : "Show raw JSON payload")
            }
        }
        .padding(.horizontal, 6)
        .padding(.vertical, 4)
        .background(model.theme.tokens.surface.opacity(0.6), in: RoundedRectangle(cornerRadius: 6))
    }

    private var diffContent: some View {
        ScrollView([.horizontal, .vertical]) {
            VStack(alignment: .leading, spacing: 1) {
                ForEach(diff.lines) { line in
                    diffRow(line)
                }
            }
            .padding(.vertical, 4)
            .frame(maxWidth: .infinity, alignment: .leading)
        }
        .frame(maxHeight: maxHeight)
        .background(model.theme.tokens.surface.opacity(0.3), in: RoundedRectangle(cornerRadius: 6))
        .textSelection(.enabled)
    }

    @ViewBuilder
    private func diffRow(_ line: ToolFileDiff.DiffLine) -> some View {
        HStack(alignment: .top, spacing: 4) {
            // Line numbers gutter
            HStack(spacing: 4) {
                Text(line.oldLineNumber.map { String($0) } ?? "")
                    .frame(width: 24, alignment: .trailing)
                Text(line.newLineNumber.map { String($0) } ?? "")
                    .frame(width: 24, alignment: .trailing)
            }
            .font(.system(size: 10, design: .monospaced))
            .foregroundStyle(model.theme.tokens.muted.opacity(0.7))

            // Prefix (+, -, space)
            Text(line.kind == .addition ? "+" : (line.kind == .deletion ? "-" : " "))
                .font(.system(size: 11, weight: .bold, design: .monospaced))
                .foregroundStyle(
                    line.kind == .addition
                        ? Caprine.Semantic.success
                        : (line.kind == .deletion ? Caprine.Semantic.danger : model.theme.tokens.muted)
                )
                .frame(width: 10, alignment: .center)

            // Content text
            Text(line.text.isEmpty ? " " : line.text)
                .font(.system(size: 11, design: .monospaced))
                .foregroundStyle(model.theme.tokens.ink)
                .frame(maxWidth: .infinity, alignment: .leading)
        }
        .padding(.horizontal, 6)
        .padding(.vertical, 1)
        .background(rowBackground(for: line.kind))
    }

    @ViewBuilder
    private func rowBackground(for kind: ToolFileDiff.DiffLine.Kind) -> some View {
        switch kind {
        case .addition:
            Caprine.Semantic.success.opacity(0.12)
        case .deletion:
            Caprine.Semantic.danger.opacity(0.12)
        case .context:
            Color.clear
        }
    }
}
